
EMU_PLATFORM = qemu

QEMU_CPU_TYPE_loongarch64 = la464
QEMU_FLAGS_loongarch64 = -machine virt -nographic -m $(if $(CONFIG_LOONGARCH_RAM_SIZE_MB),$(CONFIG_LOONGARCH_RAM_SIZE_MB)M,256M)
QEMU_loongarch64 = qemu-system-loongarch64

DEBUG_SCRIPT = qemu.sh

debugserver: QEMU_EXTRA_FLAGS += -s -S
debugserver: qemu
